"""Generate the "ForestSpans" table (span -> number of maximal constituency
trees it appears in) from the corrected Bron-Kerbosch laminar-family
enumeration in scripts/analysis/laminar_analysis.py.

The table originally in ChichewaWordhood.tex (\\label{ForestSpans}) was
generated by scripts/exploratory/treeTraversal.py, an earlier, buggier
tree-builder that undercounts: two confirmed bugs (a stale-variable reuse in
traverse() and a premature return in getEnclosingParent() that skips valid
sibling candidates) silently prune large parts of the real tree space,
producing only 16 maximal trees for nyan1308 where the correct enumeration
(independently verified two ways, see docs/VERIFICATION.md) finds 69. This
script regenerates the same table from that correct enumeration instead.

Layer numbers replicate the df.plot() convention of domain_charts-cgpt.r
(archived in OlderFiles/planarsviz_superseded/scripts/) exactly,
so they mean the same thing as "Layer" everywhere else this project uses it
(the pooled plot, the exemplary trees): sort the dataset's unique spans by
(Size ascending, Left_Edge ascending), assign 1..N, then invert
(Reverse_Layer = N + 1 - Layer) so layer 1 is the largest span. That
Reverse_Layer is what actually gets displayed as "Layer" everywhere in the
project, including here.

Two outputs, both to NonCollaborative/results/:

- nyan1308_forestspans_table.tex -- manuscript-ready fragment using the same
  \\Hline/\\mc macros as ChichewaWordhood.tex itself (a paste-in replacement
  for the existing \\label{ForestSpans} table), not self-contained.
- nyan1308_forestspans_slide.pdf (+ .tex source) -- cropped standalone PDF at
  slide-appropriate large font. Self-contained: defines its own plain
  \\Hline/\\mc, Times New Roman via fontspec (matching the manuscript's own
  font setup), and forces a solid white background via a tikz-filled node
  wrapping the table -- the same trick make_planar_latex.py's
  PDF_WRAPPER_CROPPED uses, needed because a bare `standalone`-class
  \\pagecolor doesn't survive the bounding-box crop (confirmed there via
  pdftocairo -transp: the crop leaves it actually transparent, not white).

The chart of these same rows is drawn by the planarsviz package
(plot_forestspans()) from the bundle export_planarsviz_data.py writes.

Needs xelatex on PATH (required for fontspec/Times New Roman) for the slide
PDF. Pass --tex-only to skip rendering it and just write the source files.

Usage:
    python make_forestspans_table.py
    python make_forestspans_table.py --tex-only
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results")
ANALYSIS_DIR = os.path.join(os.path.dirname(__file__), "analysis")
DOMAINS_DIR = os.path.join(os.path.dirname(__file__), "..", "domains")

sys.path.insert(0, ANALYSIS_DIR)

# Font setup lifted verbatim from ChichewaWordhood.tex:15-20 -- see
# make_planar_latex.py's identical constant for the full rationale.
FONT_SETUP = r"""\usepackage{fontspec}
\setmainfont[
  Ligatures=TeX,
  SmallCapsFont={TeX Gyre Termes},
  SmallCapsFeatures={Letters=SmallCaps},
]{Times New Roman}"""

# Self-contained cropped wrapper for the slide render. See module docstring
# for why the white fill has to be a tikz node inside the measured content
# rather than \pagecolor.
SLIDE_WRAPPER = r"""\documentclass[preview,border=14pt]{standalone}
\usepackage{array}
\usepackage{tikz}
""" + FONT_SETUP + r"""
\newcommand{\Hline}{\noalign{\vspace{2pt}\hrule height 1pt\vspace{4pt}}}
\newcommand{\mc}[3]{\multicolumn{#1}{#2}{#3}}
\renewcommand{\arraystretch}{1.5}
\begin{document}
\begin{tikzpicture}
\node[fill=white, inner sep=4pt] {
\Large
%(body)s
};
\end{tikzpicture}
\end{document}
"""


def compute_forest_spans(domain_file="domains_nyan1308.tsv"):
    """Run the corrected laminar-family enumeration and return sorted rows.

    Returns (rows, n_families):
      - rows: list of (layer, left, right, count) tuples, sorted the same way
        the original table appears to be (count descending; ties broken by
        layer ascending, since the original's tie order wasn't a deliberate
        choice).
    """
    import laminar_analysis as la

    result = la.main(
        domain_file=domain_file,
        domains_dir=DOMAINS_DIR,
        show_trees=False,
    )
    spans = result["spans"]
    span_family_count = result["span_family_count"]
    n_families = result["n_families"]

    # Replicate df.plot()'s Layer assignment (see module docstring).
    ordered = sorted(spans, key=lambda s: (s.size, s.left))
    n = len(ordered)
    reverse_layer = {(s.left, s.right): n + 1 - i for i, s in enumerate(ordered, start=1)}

    rows = [
        (reverse_layer[(s.left, s.right)], s.left, s.right, span_family_count.get(s, 0))
        for s in spans
    ]
    rows.sort(key=lambda r: (-r[3], r[0]))

    return rows, n_families


def make_table_body(rows):
    lines = [r"\begin{table}", r"\centering", r"\begin{tabular}{l>{[}l<{]}r}", r"\Hline",
             r"\textsc{layer} &  \mc{1}{l}{\textsc{span}} & \mc{1}{l}{\textsc{count}} \\", r"\Hline"]
    for layer, left, right, count in rows:
        # Non-raw string so \t is an actual tab, not the two literal characters "\t"
        # (a raw-string %-format bug here would silently emit "\t" as a broken LaTeX
        # control sequence -- caught before this shipped, kept as a plain string).
        lines.append("%d\t&\t%d--%d & %d \\\\" % (layer, left, right, count))
    lines += [r"\Hline", r"\end{tabular}",
              r"\caption{Number of trees each domain appears in within the constituency forest \label{ForestSpans}}",
              r"\end{table}"]
    return "\n".join(lines) + "\n"


def make_tabular_only(rows):
    """Just the tabular environment, no \\begin{table}/\\caption -- for the slide render."""
    lines = [r"\begin{tabular}{l>{[}l<{]}r}", r"\Hline",
             r"\textsc{layer} &  \mc{1}{l}{\textsc{span}} & \mc{1}{l}{\textsc{count}} \\", r"\Hline"]
    for layer, left, right, count in rows:
        lines.append("%d\t&\t%d--%d & %d \\\\" % (layer, left, right, count))
    lines += [r"\Hline", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def render_pdf(tex_fragment, out_pdf_path):
    wrapper = SLIDE_WRAPPER % {"body": tex_fragment}
    with tempfile.TemporaryDirectory() as tmpdir:
        wrapper_path = os.path.join(tmpdir, "wrapper.tex")
        with open(wrapper_path, "w") as f:
            f.write(wrapper)
        try:
            result = subprocess.run(
                ["xelatex", "-interaction=nonstopmode", "-halt-on-error",
                 "-output-directory", tmpdir, wrapper_path],
                capture_output=True, text=True,
            )
        except FileNotFoundError:
            print("xelatex not found on PATH -- skipping PDF render for %s" % out_pdf_path)
            return False
        if result.returncode != 0:
            print("xelatex failed for %s; last lines of output:" % out_pdf_path)
            print("\n".join(result.stdout.splitlines()[-20:]))
            return False
        shutil.copy(os.path.join(tmpdir, "wrapper.pdf"), out_pdf_path)
        return True


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--domain-file", default="domains_nyan1308.tsv")
    parser.add_argument("--tex-only", action="store_true", help="Skip PDF rendering, just write the .tex files")
    args = parser.parse_args()

    rows, n_families = compute_forest_spans(args.domain_file)
    print(f"{n_families} maximal laminar families; {len(rows)} distinct spans")

    os.makedirs(RESULTS_DIR, exist_ok=True)

    manuscript_tex = make_table_body(rows)
    manuscript_path = os.path.join(RESULTS_DIR, "nyan1308_forestspans_table.tex")
    with open(manuscript_path, "w") as f:
        f.write(manuscript_tex)
    print("Wrote %s" % manuscript_path)

    slide_tabular = make_tabular_only(rows)
    slide_tex_path = os.path.join(RESULTS_DIR, "nyan1308_forestspans_slide.tex")
    with open(slide_tex_path, "w") as f:
        f.write(slide_tabular)
    print("Wrote %s" % slide_tex_path)

    if not args.tex_only:
        slide_pdf_path = os.path.join(RESULTS_DIR, "nyan1308_forestspans_slide.pdf")
        if render_pdf(slide_tabular, slide_pdf_path):
            print("Wrote %s" % slide_pdf_path)


if __name__ == "__main__":
    main()
