"""Generate a ghost-overlay diagram of randomly sampled n-ary trees over N leaves
(positions), illustrating how vast the A001003 (little Schröder number) tree space
is compared to the handful of laminar families actually observed for a language.

Reuses the exact rendering convention already established in
NonCollaborative/results/laminar_conflict_groups.r (generated by
scripts/analysis/laminar_analysis.py) for its "ghost overlay" panels: each tree is
a read.tree() Newick string with the same fixed leaf order, drawn via
ggtree(..., layout='slanted') + layout_dendrogram(), its edge layer's alpha set very
low and colour forced to 'black' (so multiple trees are already inherently greyscale
by construction -- edges that recur across many sampled trees accumulate opacity),
and all trees stacked onto one shared patchwork grid cell (identical area() for
every tree) so they visually overlay into a single panel. No groupOTU/branch-size
mapping is used here (unlike the conflict-groups script) -- there is no target span
to highlight for a purely combinatorial illustration, so every edge gets uniform
thickness.

Trees are NOT enumerated (A001003(22) = 47,574,827,600,981 -- computationally and
visually infeasible) -- they're sampled uniformly at random from the full space of
valid n-ary ordered trees with N leaves, using the standard recursive/weighted
method: at each split, choose among the possible (first-subtree-size, rest) options
weighted by how many completions each contributes (from catalan.py's own counting
recurrence), which yields an exactly-uniform sample over the whole space.

Usage:
    python random_tree_overlay.py                  # 200 trees, 22 leaves (default)
    python random_tree_overlay.py --n-trees 300 --n-leaves 22 --alpha 0.015
    python random_tree_overlay.py --seed 7          # reproducible sample

Output goes to NonCollaborative/results/ as nyan1308_random_tree_overlay.r (+ .pdf).
"""

import argparse
import os
import random
import sys

# catalan.py lives in ../exploratory, not this directory -- import its (verified
# correct, post-A007052-fix) counting functions directly rather than re-deriving
# the same recurrence a second time.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "exploratory"))
from catalan import all_trees_new, _ordered_forests  # noqa: E402

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "results")

# Same 22 ChichPlan position labels already used for the x-axis in
# NonCollaborative/results/laminar_spanchart.r (pos_labels_vec) -- reused verbatim
# rather than the differently-abbreviated Position_Label set from planar_nyan1308.tsv
# (QM/PrS/Su/... vs. this script's QM/PreSbj/Sbj/...), since this is an R/ggtree
# diagram and that's the established convention on the R side specifically.
POSITION_LABELS = [
    "QM", "PreSbj", "Sbj", "PostSbj", "Neg1", "SM", "Neg2", "TAM", "OM", "Root",
    "Ext", "STAT", "CAUS", "APPL", "REC", "PASS", "FV", "2P", "Enc", "Obj1", "Obj2", "PostObj",
]


def _weighted_choice(options, weights, rng):
    return rng.choices(options, weights=weights, k=1)[0]


def sample_forest(n, rng):
    """A uniformly random ordered sequence of >=1 trees covering n leaves total."""
    if n == 0:
        return []
    # Matches _ordered_forests(n)'s own recurrence term-for-term, so weighting a
    # choice of j by all_trees_new(j) * _ordered_forests(n - j) samples exactly
    # proportional to how many completions each choice contributes -- the standard
    # trick for turning a counting recurrence into a uniform sampler.
    options = list(range(1, n + 1))
    weights = [all_trees_new(j) * _ordered_forests(n - j) for j in options]
    j = _weighted_choice(options, weights, rng)
    return [sample_tree(j, rng)] + sample_forest(n - j, rng)


def sample_tree(n, rng):
    """A uniformly random rooted ordered tree with n leaves (each internal node >=2 children)."""
    if n == 1:
        return 1  # placeholder leaf value; real position numbers assigned after sampling
    options = list(range(1, n))
    weights = [all_trees_new(j) * _ordered_forests(n - j) for j in options]
    j = _weighted_choice(options, weights, rng)
    return [sample_tree(j, rng)] + sample_forest(n - j, rng)


def _label_leaves(tree, counter):
    """Replace placeholder leaf values with sequential position numbers 1..n, left to right."""
    if isinstance(tree, int):
        counter[0] += 1
        return counter[0]
    return [_label_leaves(c, counter) for c in tree]


def _leftmost(tree):
    return tree if isinstance(tree, int) else _leftmost(tree[0])


def _rightmost(tree):
    return tree if isinstance(tree, int) else _rightmost(tree[-1])


def to_newick(tree, leaf_labels=None):
    """Newick string with internal node label = "L-R" span (numeric, matching the
    convention in laminar_conflict_groups.r -- not displayed anywhere in this
    script's output, just structural bookkeeping) and leaf = leaf_labels[position-1]
    if given, else the bare position number. leftmost/rightmost are always computed
    from the underlying position number regardless of what text a leaf displays, so
    swapping in name labels doesn't disturb the span bookkeeping."""
    if isinstance(tree, int):
        return leaf_labels[tree - 1] if leaf_labels else str(tree)
    inner = ",".join(to_newick(c, leaf_labels) for c in tree)
    label = "%d-%d" % (_leftmost(tree), _rightmost(tree))
    return "(%s)%s" % (inner, label)


def sample_labeled_tree(n_leaves, rng):
    tree = sample_tree(n_leaves, rng)
    return _label_leaves(tree, [0])


R_TREE_TEMPLATE = """rt_tree%(i)d <- read.tree(text="%(newick)s;")
rt_tp%(i)d <- ggtree(rt_tree%(i)d, layout='slanted', ladderize=FALSE) +
  layout_dendrogram() +
  theme(panel.background=element_blank(),
    plot.background=element_blank(),
    legend.position='none')
rt_tp%(i)d$layers[[1]]$aes_params$alpha <- %(alpha)s
rt_tp%(i)d$layers[[1]]$aes_params$colour <- 'black'
"""


def make_r_script(trees, alpha, n_leaves, out_pdf_path):
    # Leaves stay bare position numbers in the Newick, same as laminar_freqtree.r's
    # own freq_tree -- that script looks names up via a separate posLabel list rather
    # than baking them into the tree text, which is what lets it show number and name
    # together (see the geom_tiplab call below). Position labels only make sense for
    # the actual 22-position Chichewa template; fall back to bare numbers with no name
    # lookup for any other --n-leaves value.
    named = n_leaves == len(POSITION_LABELS)

    lines = [
        "library(ape)",
        "library(ggplot2)",
        "library(ggtree)",
        "library(patchwork)",
        "",
    ]
    if named:
        pos_label_entries = ", ".join(
            '"%d" = "%s"' % (i, label) for i, label in enumerate(POSITION_LABELS, 1)
        )
        lines.append("posLabel <- list(%s)" % pos_label_entries)
        lines.append("")

    for i, tree in enumerate(trees, 1):
        newick = to_newick(tree)
        lines.append(R_TREE_TEMPLATE % {"i": i, "newick": newick, "alpha": alpha})

    # Tip labels: added once, on the last tree drawn (so the label layer renders on
    # top of all 200 trees' edges instead of underneath most of them), not once per
    # tree -- every tree shares the same leaf order, so their tip positions after
    # layout_dendrogram() line up exactly and one label layer covers all of them.
    # Styling copied from laminar_freqtree.r's geom_tiplab call (geom='label' boxed
    # style, size, angle=0, hjust=0.5, label.size=0, two-line "number\nname" text,
    # lineheight) rather than the plain rotated text used before -- except offset.
    #
    # Direction verified directly (not inferred from the x=0/negative-x coordinate
    # description, which is easy to get backwards): built a small isolated test tree,
    # plotted geom_tippoint() at the true tip locations alongside geom_tiplab() boxes
    # at a few trial offsets, and compared box position to the known tip marker
    # directly. offset<0 pushes the box away from the tree, past the tip, into space
    # that's always empty (every one of the 200 trees' tips align at the same x, so
    # nothing is ever drawn beyond it -- a negative offset can't hide a real crossing,
    # only add a gap below the tip); offset>0 pushes the box the other way, up into
    # the tree, toward real branch crossings; offset=0 sits the box exactly flush on
    # the tip, which still read as overlapping the vertex at this box size/line width.
    # vjust=1.25 places the box slightly farther below the vertex; offset=-1 preserves the small
    # tree-axis gap used by freqtree.r.
    n = len(trees)
    if named:
        lines.append(
            "rt_tp%d <- rt_tp%d + geom_tiplab(geom='label', size=5, angle=0,\n"
            "  offset=-1, hjust=0.5, vjust=1.25, alpha=1, label.size=0,\n"
            "  aes(label=paste(label, posLabel[label], sep=\"\\n\")), lineheight=1) +\n"
            "  theme(plot.margin=margin(t=5, r=5, b=25, l=5, unit=\"pt\"))" % (n, n)
        )
    else:
        lines.append(
            "rt_tp%d <- rt_tp%d + geom_tiplab(geom='label', size=5, angle=0,\n"
            "  offset=-1, hjust=0.5, vjust=1.25, alpha=1, label.size=0, lineheight=1) +\n"
            "  theme(plot.margin=margin(t=5, r=5, b=25, l=5, unit=\"pt\"))" % (n, n)
        )
    lines.append("")

    # Stack every tree onto the identical patchwork grid cell -- this is the actual
    # overlay mechanism (see laminar_conflict_groups.r's panel_C_design for the
    # pattern this is copied from): each tree is a fully transparent-background
    # ggplot with only its low-alpha black edges visible, so summing them with `+`
    # and mapping them all to one area() draws them stacked on top of each other.
    lines.append("overlay_design <- c(")
    lines.append(",\n".join(["  area(t=1, l=1, b=1, r=1)"] * n))
    lines.append(")")
    lines.append("overlay <- (")
    lines.append(" +\n  ".join("rt_tp%d" % i for i in range(1, n + 1)))
    lines.append(") + plot_layout(design=overlay_design)")
    lines.append("")
    # Matches laminar_freqtree.r's own ggsave call exactly (width=16, height=10,
    # default units = inches) -- confirmed directly that this is why its 22 boxed tip
    # labels don't overlap: this script's earlier width=24/height=16 *centimeters*
    # (roughly half the physical page freqtree.r uses) was too cramped for the same
    # label style at the same size, once there were 22 of them across the width.
    lines.append("ggsave('%s', overlay, width=16, height=10)" % out_pdf_path)
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--n-trees", type=int, default=200, help="Number of trees to sample (default: 200)")
    parser.add_argument("--n-leaves", type=int, default=22, help="Number of leaves per tree (default: 22)")
    parser.add_argument(
        "--alpha", type=float, default=0.02,
        help="Per-tree edge opacity (default: 0.02 -- tuned so the root edge, present in "
             "every tree, reads near-solid black across ~200 layers; lower for more trees)",
    )
    parser.add_argument("--seed", type=int, help="Random seed, for a reproducible sample")
    parser.add_argument(
        "--tex-only", "--r-only", dest="r_only", action="store_true",
        help="Only write the .r file, don't run Rscript",
    )
    args = parser.parse_args()

    rng = random.Random(args.seed)
    trees = [sample_labeled_tree(args.n_leaves, rng) for _ in range(args.n_trees)]

    os.makedirs(RESULTS_DIR, exist_ok=True)
    out_pdf_path = os.path.join(RESULTS_DIR, "nyan1308_random_tree_overlay.pdf")
    r_script = make_r_script(trees, args.alpha, args.n_leaves, out_pdf_path)

    out_r_path = os.path.join(RESULTS_DIR, "nyan1308_random_tree_overlay.r")
    with open(out_r_path, "w") as f:
        f.write(r_script)
    print("Wrote %s" % out_r_path)

    if not args.r_only:
        import subprocess
        result = subprocess.run(["Rscript", out_r_path], capture_output=True, text=True)
        print(result.stdout)
        if result.returncode != 0:
            print(result.stderr)
            raise SystemExit(result.returncode)
        print("Wrote %s" % out_pdf_path)


if __name__ == "__main__":
    main()
